"Pathogen
execute pathogen#infect()
syntax on
filetype plugin indent on

"Maximize the gvim on start
au GUIEnter * simalt ~x

"Font
set guifont=Consolas:h10:cANSI

"Visual Studio like tabbing
set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab

"Editor Properties
set number
set showcmd
set cursorline
set cursorcolumn

"BadWolf Color Scheme
colorscheme badwolf
"Makes gutters darker than the bg
let g:badwolf_darkgutter = 1
"Make tabline lighter than the bg
let g:badwolf_tabline = 2

"Nerdtree
autocmd vimenter * NERDTree
map <C-n> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

"Synastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

"CtrlP
set runtimepath^=~\vimfiles\bundle\ctrlp.vim

"Omnisharp
"let g:Omnisharp_selector_ui = 'unite'
set noshowmatch

"Omnisharp + Synastic
let g:synastic_cs_checkers = ['syntax', 'semantic', 'issues']

augroup omnisharp_commands
	autocmd!

	autocmd FileType cs nnoremap <leader>b :wa!<cr>:OmniSharpBuildAsync<cr>
	autocmd BufEnter,TextChanged,InsertLeave *.cs SyntasticCheck

	autocmd CursorHold *.cs call OmniSharp#TypeLookupWithoutDocumentation()

	autocmd FileType cs nnoremap gd :OmniSharpGotoDefinition<cr>
	autocmd FileType cs nnoremap <leader>fi :OmniSharpFindImplementations<cr>
	autocmd FileType cs nnoremap <leader>ft :OmniSharpFindType<cr>
	autocmd FileType cs nnoremap <leader>fs :OmniSharpFindSymbol<cr>
	autocmd FileType cs nnoremap <leader>fu :OmniSharpFindUsages<cr>
	"finds members in the current buffer
	autocmd FileType cs nnoremap <leader>fm :OmniSharpFindMembers<cr>
	" cursor can be anywhere on the line containing an issue
	autocmd FileType cs nnoremap <leader>x  :OmniSharpFixIssue<cr>
	autocmd FileType cs nnoremap <leader>fx :OmniSharpFixUsings<cr>
	autocmd FileType cs nnoremap <leader>tt :OmniSharpTypeLookup<cr>
	autocmd FileType cs nnoremap <leader>dc :OmniSharpDocumentation<cr>
	"navigate up by method/property/field
	autocmd FileType cs nnoremap <C-K> :OmniSharpNavigateUp<cr>
	"navigate down by method/property/field
	autocmd FileType cs nnoremap <C-J> :OmniSharpNavigateDown<cr>
augroup END

"How long to wait before fetching info
set updatetime=500
set cmdheight=2

" Branch switching, force reload OmniSharp
nnoremap <leader>r1 :OmniSharpReloadSolution<cr>
nnoremap <leader>cf :OmniSharpCodeFormat<cr>

"Syntax highlighting
nnoremap <leader>th :OmniSharpHighlightTypes<cr>
